# DO NOT use python 3.12, it could cause dependency problems
FROM python:3.11.6-bookworm

WORKDIR /workspace/yomigana-ebook

# tell git the project directory is safe
RUN git config --global --add safe.directory /workspace/yomigana-ebook

# install uv
COPY --from=ghcr.io/astral-sh/uv:0.6.0 /uv /usr/local/bin/uv

# install node.js for client development
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install -y nodejs
