FROM node:alpine as build-client

WORKDIR /build

COPY web-demo/client /build
RUN npm install && npm run build

# --------------------

# DO NOT use python 3.12, it could cause dependency problems
# DO NOT use `python:alpine` as the base image for python projects
# It could causes problems while installing packages and have a much longer building time
FROM python:3.11.6-slim-bookworm as build-webapp

WORKDIR /build

# install uv
COPY --from=ghcr.io/astral-sh/uv:0.6.0 /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock README.md .python-version ./
COPY yomigana_ebook ./yomigana_ebook

COPY web-demo/pyproject.toml web-demo/README.md ./web-demo/
COPY web-demo/web_demo ./web-demo/web_demo

WORKDIR /build/web-demo

RUN uv sync --frozen --no-dev
RUN uv run python -m unidic download

# --------------------

FROM python:3.11.6-slim-bookworm as production

WORKDIR /app

COPY --from=build-client /build/dist ./client/dist

COPY --from=build-webapp /build/.venv /app/.venv
COPY --from=build-webapp /build/yomigana_ebook ./yomigana_ebook
COPY --from=build-webapp /build/web-demo/pyproject.toml /build/web-demo/README.md ./
COPY --from=build-webapp /build/web-demo/web_demo ./web_demo

ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT ["python", "-m", "uvicorn", "web_demo.main:app"]
